Add file system utility to parse XML files
oliverschwendener/ueli pull request #1199
Opened 2024-09-12 14:13 UTC by scomans

Adds XML reader function to file system utility used by updated Jetbrains Toolbox extension (https://github.com/scomans/ueli/commit/ee2f4ab40ed7ede3d216f4bbc5e6928962d8461a).

2024-09-12 21:53 UTC, oliverschwendener commented
I know that we have "readJsonFile" and "writeJsonFile" in the file system utility, but as we're introducing a new npm package here I would love to have the XML parsing in a separate module, similar to the `IniFileParser`. So if you have to read an xml file and parse it you would have to use the FileSystemUtility first to read the text file and then parse the XML using the XmlFileParser. Can you move the XML parsing out of the FileSystemUtility into it's separate module? Let me know if you need help setting up the module.

2024-09-12 21:54 UTC, oliverschwendener requested changes
See my comment above

2024-09-12 21:58 UTC, scomans commented
Will do that tomorrow morning

2024-09-13 06:00 UTC, oliverschwendener commented
I added the basic structure how I think it would suit best. I would be happy if you could have a look and add some description for the XmlParser.

2024-09-13 06:19 UTC, scomans commented
Looks good to me

2024-09-13 06:48 UTC, oliverschwendener commented on src/main/Core/XmlParser/Contract/XmlParser.ts
> +     * @returns {T} - The parsed result.
Very nice, thanks! 💪

2024-09-13 06:49 UTC, oliverschwendener approved these changes

2024-09-13 06:51 UTC, oliverschwendener commented
Would you like to be the code owner of this module? Then all future changes can be reviewed by you

2024-09-13 07:36 UTC, scomans commented
Sure :)

2024-09-13 08:06 UTC, oliverschwendener approved these changes

2024-09-13 08:13 UTC, merged