feat: update VSCode extension to handle macOS file URIs correctly
oliverschwendener/ueli pull request #1294
Opened 2024-12-13 22:32 UTC by meghoshpritam

This pull request includes updates to the `VSCodeExtension` class in the `src/main/Extensions/VSCode/VSCodeExtension.ts` file to handle command arguments more effectively based on the operating system. The changes ensure that file URIs are correctly formatted for macOS.

* Added logic to modify the `argument` variable to replace the file URI prefix when the operating system is macOS.
* Updated the `defaultAction` to use the newly defined `argument` variable instead of creating it inline.

2024-12-14 01:42 UTC, IrishBruse commented
Do you have an example of what this fixes I use it on Mac every day without encountering any issues with the uri

2024-12-14 06:28 UTC, meghoshpritam commented
> Do you have an example of what this fixes I use it on Mac every day without encountering any issues with the uri

@IrishBruse 

I am encountering the following error while O open the vscode folder. I removed the "" in the final command.

[12/14/2024, 11:51:45 AM][ERROR] Error while invoking action: Warning: 'folder-uri file:///Users/computer/work/kw' is not in the list of known options, but still passed to Electron/Chromium.
![image](https://github.com/user-attachments/assets/a94f7a44-7d4f-4ed3-bb97-388717fa2b0b)

2024-12-14 10:20 UTC, oliverschwendener requested changes
Please revert the changes in `package.json` and `package-lock.json`

2024-12-14 10:30 UTC, meghoshpritam commented
> Please revert the changes in `package.json` and `package-lock.json`

@oliverschwendener the changes in `package.json` and `package-lock.json` are reverted.

2024-12-15 00:05 UTC, IrishBruse requested changes

2024-12-15 00:05 UTC, IrishBruse commented on src/main/Extensions/VSCode/VSCodeExtension.ts
> +                argument: template.replace(/"?%s"?/, `${commandArg} ${uri}`),
This means optional " but thats already the case just remove the quotes from the template in the settings. Also send what template you are using

2024-12-15 00:09 UTC, IrishBruse commented on src/main/Extensions/VSCode/VSCodeExtension.ts
> +                argument: template.replace(/"?%s"?/, `${commandArg} ${uri}`),
![image](https://github.com/user-attachments/assets/21f5c845-86b5-455c-b2a9-7e808de46a57)
just remove the quotes from the template to achieve the same thing

2024-12-15 00:10 UTC, IrishBruse commented
: Warning: 'folder-uri file:///Users/computer/work/kw' is not in the list of known options, but still passed to Electron/Chromium. not sure how this would be happening as what it should be passing is '--folder-uri file:///Users/computer/work/kw'

2024-12-21 05:09 UTC, closed without merging