Execute workflow commands in default terminal
oliverschwendener/ueli pull request #670
Opened 2021-03-23 14:37 UTC by underthecocotree

Hi,

While working with the Workflows I noticed that the commands where not firing in the terminal.  Maybe it is the kind of commands I wanted to run - but not much seemed to be happening for me.

The workflow command is now mimicking the commandline-plugin.  This change has been tested with iTerm on a Mac.  I noticed that if there are a few commands back to back they will execute on the same window. 

Related?
https://github.com/oliverschwendener/ueli/issues/644

2021-03-23 15:21 UTC, oliverschwendener commented
Cool, thanks for your contribution! I'll have a look at this as soon as I have time 👍

2021-04-18 18:23 UTC, oliverschwendener commented on src/main/plugins/workflow-plugin/workflow-plugin.ts
> +    private commandConfig: CommandlineOptions;
Can we rename this to `commandlineOptions`? I think it would be a more accurate name.

2021-04-18 18:24 UTC, oliverschwendener requested changes
Thanks for the efforts, it works as expected. The only thing that I would like to be adressed is mentioned in the comment above.

2021-04-26 11:05 UTC, underthecocotree commented
@oliverschwendener just updated it.  I did battle with that variable name but now it makes a lot of sense.

2021-04-26 11:27 UTC, oliverschwendener approved these changes

2021-04-26 11:27 UTC, merged